/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export { }

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AboutSection: typeof import('./src/components/AboutSection.vue')['default']
    ContactSection: typeof import('./src/components/ContactSection.vue')['default']
    FooterSection: typeof import('./src/components/FooterSection.vue')['default']
    HeaderSection: typeof import('./src/components/HeaderSection.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    IconCommunity: typeof import('./src/components/icons/IconCommunity.vue')['default']
    IconDocumentation: typeof import('./src/components/icons/IconDocumentation.vue')['default']
    IconEcosystem: typeof import('./src/components/icons/IconEcosystem.vue')['default']
    IconSupport: typeof import('./src/components/icons/IconSupport.vue')['default']
    IconTooling: typeof import('./src/components/icons/IconTooling.vue')['default']
    ProjectsSection: typeof import('./src/components/ProjectsSection.vue')['default']

    TheWelcome: typeof import('./src/components/TheWelcome.vue')['default']

    WelcomeItem: typeof import('./src/components/WelcomeItem.vue')['default']
  }
}
